version: '3.7'
services:
  web:
    image: nginx:1.19.9
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/var/www/html
    container_name:
      "nginx_server"

  app:
    build: ./
    volumes:
      - ./nginx/:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    container_name:
      "php_fpm_56"


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake_db
      MYSQL_USER: cake
      MYSQL_PASSWORD: cake
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    container_name:
      "mysql_57"
